language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.1


addons:
  apt:
     packages:
      - scons
      - libboost-all-dev
      - libboost-regex-dev
      - libatlas-base-dev
      - libnetcdf-dev
      - swig
      - python3-dev
      - python3-numpy
      - python3-scipy
      - libeigen3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install netcdf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install eigen; fi

script: scons

  
